#!/usr/bin/env ts-node
/**
 * cosmos-doctor — KSM∞ scaffold + verification CLI for cosmos-system-5
 *
 * Generated by /ksm-infinity at meta-level nn² (Mutation M-07 + M-08).
 * Purpose: replace per-service hand-patching with a generative,
 *          replayable, structure-preserving scaffolder.
 *
 * Usage:
 *   ts-node tools/cosmos-doctor.ts scan        # report missing artefacts
 *   ts-node tools/cosmos-doctor.ts scaffold    # generate Dockerfile/README/test
 *   ts-node tools/cosmos-doctor.ts verify      # invariant check (CI-friendly)
 *
 * Exit codes:
 *   0 — all 18 services pass
 *   1 — at least one service fails an invariant
 *   2 — infrastructure missing (api-gateway, shared-libraries)
 */
import * as fs from 'fs';
import * as path from 'path';

interface ServiceManifest {
  id: string;            // e.g. "T-7"
  triad: 'cerebral' | 'somatic' | 'autonomic';
  dir: string;           // relative to repo root
  port: number;
  polarity: 'sympathetic' | 'parasympathetic' | 'somatic';
  dimension: '[2-7]' | '[5-4]' | '[8-1]';
  position: 'development'|'treasury'|'production'|'organization'|'sales'|'market';
  shared?: boolean;
}

// Single source of truth for the 18-service topology.
const TOPOLOGY: ServiceManifest[] = [
  // Cerebral
  {id:'T-7', triad:'cerebral', dir:'cerebral-triad/thought-service',      port:3001, polarity:'sympathetic',     dimension:'[2-7]', position:'treasury'},
  {id:'PD-2',triad:'cerebral', dir:'cerebral-triad/processing-director',  port:3002, polarity:'parasympathetic', dimension:'[2-7]', position:'development'},
  {id:'P-5', triad:'cerebral', dir:'cerebral-triad/processing-service',   port:3003, polarity:'somatic',         dimension:'[5-4]', position:'production'},
  {id:'O-4', triad:'cerebral', dir:'cerebral-triad/output-service',       port:3004, polarity:'somatic',         dimension:'[5-4]', position:'organization'},
  {id:'S-8', triad:'cerebral', dir:'cerebral-triad/sales-service',        port:3005, polarity:'somatic',         dimension:'[8-1]', position:'sales'},
  {id:'M-1', triad:'cerebral', dir:'cerebral-triad/market-service',       port:3006, polarity:'somatic',         dimension:'[8-1]', position:'market'},
  // Somatic
  {id:'PD-2',triad:'somatic',  dir:'somatic-triad/development-service',   port:3015, polarity:'parasympathetic', dimension:'[2-7]', position:'development', shared:true},
  {id:'T-7', triad:'somatic',  dir:'somatic-triad/treasury-service',      port:3016, polarity:'parasympathetic', dimension:'[2-7]', position:'treasury',    shared:true},
  {id:'P-5', triad:'somatic',  dir:'somatic-triad/processing-service',    port:3013, polarity:'somatic',         dimension:'[5-4]', position:'production'},
  {id:'O-4', triad:'somatic',  dir:'somatic-triad/output-service',        port:3014, polarity:'sympathetic',     dimension:'[5-4]', position:'organization'},
  {id:'S-8', triad:'somatic',  dir:'somatic-triad/sensory-service',       port:3012, polarity:'somatic',         dimension:'[8-1]', position:'sales'},
  {id:'M-1', triad:'somatic',  dir:'somatic-triad/motor-control-service', port:3011, polarity:'sympathetic',     dimension:'[8-1]', position:'market'},
  // Autonomic
  {id:'PD-2',triad:'autonomic',dir:'autonomic-triad/process-director',    port:3023, polarity:'parasympathetic', dimension:'[2-7]', position:'development'},
  {id:'T-7', triad:'autonomic',dir:'autonomic-triad/trigger-service',     port:3025, polarity:'sympathetic',     dimension:'[2-7]', position:'treasury'},
  {id:'P-5', triad:'autonomic',dir:'autonomic-triad/processing-service',  port:3024, polarity:'somatic',         dimension:'[5-4]', position:'production'},
  {id:'O-4', triad:'autonomic',dir:'autonomic-triad/organization-service',port:3026, polarity:'somatic',         dimension:'[5-4]', position:'organization'},
  {id:'S-8', triad:'autonomic',dir:'autonomic-triad/state-management-service', port:3022, polarity:'parasympathetic', dimension:'[8-1]', position:'sales'},
  {id:'M-1', triad:'autonomic',dir:'autonomic-triad/monitoring-service',  port:3021, polarity:'parasympathetic', dimension:'[8-1]', position:'market'},
];

const REQUIRED_ARTIFACTS = ['Dockerfile', 'README.md', 'src'] as const;
const REQUIRED_TEST_GLOB = /\.(test|spec)\.ts$/;

function scanService(s: ServiceManifest): string[] {
  const issues: string[] = [];
  for (const a of REQUIRED_ARTIFACTS) {
    if (!fs.existsSync(path.join(s.dir, a))) issues.push(`missing ${a}`);
  }
  const srcDir = path.join(s.dir, 'src');
  if (fs.existsSync(srcDir)) {
    const hasTest = fs.readdirSync(srcDir).some(f => REQUIRED_TEST_GLOB.test(f));
    if (!hasTest) issues.push('no *.test.ts or *.spec.ts');
  }
  return issues;
}

function dockerfileFor(s: ServiceManifest): string {
  return `# Generated by cosmos-doctor scaffold (KSM∞ nn² mutation)
FROM node:18-alpine AS build
WORKDIR /workspace
COPY package.json package-lock.json tsconfig.json ./
COPY cognitive-core/shared-libraries ./cognitive-core/shared-libraries
COPY ${s.dir} ./${s.dir}
RUN npm install --workspaces --include-workspace-root \\
 && npm --workspace @cosmos/cognitive-core-shared-libraries run build \\
 && npm --workspace ${s.dir} run build

FROM node:18-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production PORT=${s.port} SERVICE_NAME=${path.basename(s.dir)} \\
    TRIAD=${s.triad} SERVICE_TYPE=${s.id} POLARITY=${s.polarity} DIMENSION=${s.dimension}
COPY --from=build /workspace/cognitive-core/shared-libraries/dist /app/node_modules/@cosmos/cognitive-core-shared-libraries/dist
COPY --from=build /workspace/cognitive-core/shared-libraries/package.json /app/node_modules/@cosmos/cognitive-core-shared-libraries/package.json
COPY --from=build /workspace/${s.dir}/dist ./dist
COPY --from=build /workspace/${s.dir}/package.json ./
RUN npm install --omit=dev
HEALTHCHECK --interval=15s --timeout=5s --retries=3 \\
  CMD wget -qO- http://localhost:${s.port}/health | grep -q '"status":"healthy"' || exit 1
EXPOSE ${s.port}
USER node
CMD ["node", "dist/index.js"]
`;
}

function readmeFor(s: ServiceManifest): string {
  return `# ${path.basename(s.dir)} (${s.id}) · ${s.triad[0].toUpperCase()+s.triad.slice(1)} Triad

> Polarity: **${s.polarity}** · Dimension: **${s.dimension}** · Position: **${s.position}**${s.shared ? ' · Shared parasympathetic' : ''}
> Port: \`${s.port}\`

Generated by \`cosmos-doctor\` (KSM∞ Mutation M-07/M-08, meta-level nn²).

## Endpoints
- \`GET /health\`    — real readiness (event-bus + dependencies)
- \`GET /metrics\`   — Prometheus exposition (consumed by autonomic-monitoring M-1)
- \`POST /\`         — service-specific contract (see \`src/${path.basename(s.dir)}.ts\`)

## Topology
This service is the **${s.position}** position of the **${s.dimension}** dimension in the
**${s.triad}** triad of the C-S-A [3-6-9] ennead.
`;
}

function testStubFor(s: ServiceManifest): string {
  const cls = path.basename(s.dir).split('-').map(p=>p[0].toUpperCase()+p.slice(1)).join('');
  return `import { ${cls} } from './${path.basename(s.dir)}';
import { ServiceConfig } from '@cosmos/cognitive-core-shared-libraries';
const cfg: ServiceConfig = { port:${s.port}, serviceName:'${path.basename(s.dir)}', triadType:'${s.triad}', serviceType:'${s.id}', environment:'test' };
describe('${cls} (${s.id}) — ${s.triad} ${s.dimension}', () => {
  it('reports healthy after init', async () => {
    const svc = new ${cls}(cfg); await svc.initialize();
    expect(svc.getHealth().status).toMatch(/healthy|degraded/);
    await svc.shutdown?.();
  });
});
`;
}

async function main() {
  const cmd = process.argv[2] ?? 'scan';
  let failures = 0;
  for (const s of TOPOLOGY) {
    const issues = scanService(s);
    if (issues.length === 0) continue;
    failures++;
    if (cmd === 'scan' || cmd === 'verify') {
      console.log(`✗ ${s.dir} [${s.id} ${s.triad}/${s.dimension}]`);
      issues.forEach(i => console.log(`    - ${i}`));
    } else if (cmd === 'scaffold') {
      if (!fs.existsSync(path.join(s.dir, 'Dockerfile')))
        fs.writeFileSync(path.join(s.dir, 'Dockerfile'), dockerfileFor(s));
      if (!fs.existsSync(path.join(s.dir, 'README.md')))
        fs.writeFileSync(path.join(s.dir, 'README.md'), readmeFor(s));
      const srcDir = path.join(s.dir, 'src');
      if (fs.existsSync(srcDir)) {
        const hasTest = fs.readdirSync(srcDir).some(f => REQUIRED_TEST_GLOB.test(f));
        if (!hasTest)
          fs.writeFileSync(path.join(srcDir, `${path.basename(s.dir)}.test.ts`), testStubFor(s));
      }
      console.log(`✓ scaffolded ${s.dir}`);
    }
  }
  if (cmd === 'verify' && failures > 0) process.exit(1);
  if (cmd !== 'scaffold') {
    console.log(`\n${failures}/${TOPOLOGY.length} services need attention.`);
  }
}

main().catch(e => { console.error(e); process.exit(2); });
